# -*- coding: utf-8 -*-
"""WS3-331.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XYbV02sN5JKMiyUVmiCk0Gpbrh-3_b9
"""

from bs4 import BeautifulSoup
import requests

url = "https://www.nytimes.com/section/science"

page = BeautifulSoup(requests.get(url).text, "lxml") 

for headlines in page.find_all(class_="css-1kv6qi e15t083i0"):
    print(headlines.text.strip())
#for headlines in page.find_all(class_="css-1kv6qi e15t083i0"):
#     print(headlines.text.strip())
# d = page.find_all('div', class_='css-e0xall e15t083i3')
# for item in d:
#     # Find <span> in each item. If not exists x will be None
#     x = item.find('span')
#     # Check if x is not None and then only print
#     print(x.text.strip())

# divs = page.find_all("div.css-e0xall")
# for item in divs:
#     try:
#         print(item.find('span').text.strip())
#     except AttributeError:
#         print("Item Not available")


# for headlines in page.find_all(class_="css-e0xall"):
#      print(headlines.text.strip())

divs = page.find_all(class_="css-e0xall e15t083i3")
divs